FROM node:20-alpine AS base

WORKDIR /app

COPY package*.json ./
RUN npm ci --only=production

COPY backend ./backend

USER node

EXPOSE 3001

ENV NODE_ENV=production

CMD ["node", "backend/server.js"]
