version: '3.8'

services:
  backend:
    build:
      context: ../../
      dockerfile: infra/docker/Dockerfile.backend.prod
    container_name: bolao-backend-prod
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - PIN=${PIN}
      - PORT=3001
      - NODE_ENV=production

  frontend:
    build:
      context: ../../
      dockerfile: infra/docker/Dockerfile.frontend.prod
    container_name: bolao-frontend-prod
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
