export const AVATARS = [
  { name: 'Pizza', emoji: '🍕' },
  { name: 'Hambúrguer', emoji: '🍔' },
  { name: 'Sushi', emoji: '🍣' },
  { name: 'Taco', emoji: '🌮' },
  { name: 'Donut', emoji: '🍩' },
  { name: 'Cupcake', emoji: '🧁' },
  { name: 'Hot Dog', emoji: '🌭' },
  { name: 'Pasta', emoji: '🍝' },
  { name: 'Frango', emoji: '🍗' },
  { name: 'Sorvete', emoji: '🍦' },
  { name: 'Morango', emoji: '🍓' },
  { name: 'Uva', emoji: '🍇' },
  { name: 'Macaco', emoji: '🐒' },
  { name: 'Cachorro', emoji: '🐶' },
  { name: 'Gato', emoji: '🐱' },
  { name: 'Coelho', emoji: '🐰' },
  { name: 'Urso', emoji: '🐻' },
  { name: 'Panda', emoji: '🐼' },
  { name: 'Raposa', emoji: '🦊' },
  { name: 'Ovelha', emoji: '🐑' },
  { name: 'Porco', emoji: '🐷' },
  { name: 'Vaca', emoji: '🐮' },
  { name: 'Cavalo', emoji: '🐴' },
  { name: 'Unicórnio', emoji: '🦄' },
  { name: 'Dragão', emoji: '🐉' },
  { name: 'Fantasma', emoji: '👻' },
  { name: 'Alienígena', emoji: '👽' },
  { name: 'Robô', emoji: '🤖' },
  { name: 'Ninja', emoji: '🥷' },
  { name: 'Mago', emoji: '🧙' },
  { name: 'Princesa', emoji: '👸' },
  { name: 'Super-herói', emoji: '🦸' },
];
